{% set name = "aurora" %}
{% set version = "0.4.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aurora-{{ version }}.tar.gz
  sha256: e2a84020226d7bb81685b174a8352a77d175a4432a5e5863a1909cd4dcd56248

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python >=3.8
  run:
    - matplotlib-base
    - mt-metadata
    - mth5
    - mtpy-v2
    - numba
    - numpy
    - obspy
    - pandas ==1.4.4
    - psutil
    - python >=3.8
    - scipy
    - xarray

test:
  imports:
    - aurora
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/simpeg/aurora
  summary: Processing Codes for Magnetotelluric Data
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kkappler
    - kujaku11
    - lheagy
