{% set name = "aurora" %}
{% set version = "0.3.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aurora-{{ version }}.tar.gz
  sha256: 01fca52621c41361dde5d177662d7768ff355190c32136a11eaad46656e430b3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python >=3.5
  run:
    - matplotlib-base
    - numba
    - numpy
    - obspy
    - pandas
    - python >=3.5
    - scipy
    - xarray

test:
  imports:
    - aurora
    - aurora.signal
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/simpeg/aurora
  summary: Processing Codes for Magnetotelluric Data
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kkappler
    - kujaku11
    - lheagy
