{% set name = "aurora" %}
{% set version = "0.3.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aurora-{{ version }}.tar.gz
  sha256: 9d300f9c97cf10ad85e74a036e1c93ac4e06992279c1b72019da5aee9bb43010

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python >=3.8
  run:
    - matplotlib-base
    - mt-metadata
    - mth5
    - numba
    - numpy
    - obspy
    - pandas ==1.4.4
    - psutil
    - python >=3.8
    - scipy
    - xarray

test:
  imports:
    - aurora
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/simpeg/aurora
  summary: Processing Codes for Magnetotelluric Data
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kkappler
    - kujaku11
    - lheagy
